### ISSUE TITLE
Script not working with Resin OS 1.19.0

### ISSUE THREAD

**Issue by forrestp** [resin-io/resin-preload-image-script#16]
output from running script:
302+0 records in
302+0 records out
Resize '/mnt/139926' of 'max'
Waiting for Docker to start...
INFO[0000] Listening for HTTP on unix (/tmp/docker-139926/docker.sock) 
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
WARN[0000] Your kernel does not support swap memory limit. 
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=786b29d execdriver=native-0.2 graphdriver=btrfs version=1.7.1
Pulling image...
INFO[0001] POST /v1.19/images/create?fromImage=registry.resin.io%2Fnvraspiclientprodpi3%2F6d38ee194296396a23250448ca933a328c5d5b66%3Alatest 
Pulling repository registry.resin.io/nvraspiclientprodpi3/6d38ee194296396a23250448ca933a328c5d5b66
d7dd152e828a: Pulling image (latest) from registry.resin.io/nvraspiclientprodpi3d7dd152e828a: Pulling dependent layers 
db95e11b2339: Download complete 
f75c28163b13: Download complete 
3fefe884f42d: Download complete 
6faf416281c0: Download complete 
d904d974608a: Download complete 
b9af8671c5e4: Download complete 
1c14b4ee6d58: Download complete 
bee2a994133a: Download complete 
38e88551a840: Download complete 
d7dd152e828a: Download complete 
9087555f764a: Download complete 
36433eb7bda6: Download complete 
84e6e10b6635: Download complete 
91fd205fbf8b: Download complete 
54771468ff59: Download complete 
c94c620aa6da: Download complete 
6e345c48ee0a: Download complete 
c020281cc585: Download complete 
eb5f8d3f116b: Download complete 
d5089f438fea: Download complete 
99de94c1e0d6: Download complete 
ef19b406da52: Download complete 
f3e693969f49: Download complete 
e584d6e5ebfb: Download complete 
9d7f15ad7239: Download complete 
e4940f7f0020: Download complete 
141eb247ae97: Download complete 
42c342519beb: Download complete 
783cd61178fe: Download complete 
058ca2e357f9: Download complete 
a8cb89891df8: Download complete 
128daf73a3db: Download complete 
Status: Downloaded newer image for registry.resin.io/nvraspiclientprodpi3/6d38ee194296396a23250448ca933a328c5d5b66:latest
Docker images loaded:
INFO[0061] GET /v1.19/images/json?all=1                 
REPOSITORY                                                                        TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.resin.io/nvraspiclientprodpi3/6d38ee194296396a23250448ca933a328c5d5b66   latest              d7dd152e828a        30 minutes ago      666.7 MB
<none>                                                                            <none>              99de94c1e0d6        292 years ago       169.3 MB
<none>                                                                            <none>              a8cb89891df8        292 years ago       652.3 MB
<none>                                                                            <none>              c020281cc585        292 years ago       123.3 MB
<none>                                                                            <none>              f3e693969f49        292 years ago       261.1 MB
<none>                                                                            <none>              1c14b4ee6d58        292 years ago       115.1 MB
<none>                                                                            <none>              9087555f764a        292 years ago       123.3 MB
<none>                                                                            <none>              b9af8671c5e4        292 years ago       115.1 MB
<none>                                                                            <none>              d5089f438fea        292 years ago       123.3 MB
<none>                                                                            <none>              eb5f8d3f116b        292 years ago       123.3 MB
<none>                                                                            <none>              ef19b406da52        292 years ago       199.4 MB
<none>                                                                            <none>              54771468ff59        292 years ago       123.3 MB
<none>                                                                            <none>              6e345c48ee0a        292 years ago       123.3 MB
<none>                                                                            <none>              f75c28163b13        292 years ago       104.9 MB
<none>                                                                            <none>              058ca2e357f9        292 years ago       652.3 MB
<none>                                                                            <none>              783cd61178fe        292 years ago       550.2 MB
<none>                                                                            <none>              a0a9299a0016        292 years ago       123.3 MB
<none>                                                                            <none>              38e88551a840        292 years ago       123.3 MB
<none>                                                                            <none>              3fefe884f42d        292 years ago       104.9 MB
<none>                                                                            <none>              84e6e10b6635        292 years ago       123.3 MB
<none>                                                                            <none>              91fd205fbf8b        292 years ago       123.3 MB
<none>                                                                            <none>              c94c620aa6da        292 years ago       123.3 MB
<none>                                                                            <none>              d904d974608a        292 years ago       107.8 MB
<none>                                                                            <none>              db95e11b2339        292 years ago       104.9 MB
<none>                                                                            <none>              e4940f7f0020        292 years ago       459.2 MB
<none>                                                                            <none>              128daf73a3db        292 years ago       666.5 MB
<none>                                                                            <none>              42c342519beb        292 years ago       545.8 MB
<none>                                                                            <none>              bee2a994133a        292 years ago       115.1 MB
<none>                                                                            <none>              e584d6e5ebfb        292 years ago       439.2 MB
<none>                                                                            <none>              9d7f15ad7239        292 years ago       439.2 MB
<none>                                                                            <none>              141eb247ae97        292 years ago       459.2 MB
<none>                                                                            <none>              36433eb7bda6        292 years ago       123.3 MB
<none>                                                                            <none>              6faf416281c0        292 years ago       104.9 MB
Done.
Waiting for Docker to stop...INFO[0061] Processing signal 'terminated'

**Comment by forrestp** [comment]
Log messages in resin dashboard:

08.11.16 16:41:42 [-0500] Failed to download application 'registry.resin.io/nvraspiclientprodpi3/6d38ee194296396a23250448ca933a328c5d5b66' due to 'Cannot read property 'RESIN_SUPERVISOR_DELTA' of null'
08.11.16 16:41:43 [-0500] Updating application 'registry.resin.io/nvraspiclientprodpi3/6d38ee194296396a23250448ca933a328c5d5b66'
08.11.16 16:41:43 [-0500] Killing application 'registry.resin.io/nvraspiclientprodpi3/6d38ee194296396a23250448ca933a328c5d5b66'
08.11.16 16:41:43 [-0500] Killed application 'registry.resin.io/nvraspiclientprodpi3/6d38ee194296396a23250448ca933a328c5d5b66'
08.11.16 16:41:45 [-0500] Downloading application 'registry.resin.io/nvraspiclientprodpi3/6d38ee194296396a23250448ca933a328c5d5b66'

**Comment by forrestp** [comment]
After running the preload script and flashing the new (bigger) image to an SD card and booting, it looks like the device still downloads the image (goes into 'downloading' state, progress bar gradually goes to 100% before app starts)

**Comment by jhermsmeier** [comment]
@forrestp are you still having issues with this?

**Comment by jhermsmeier** [comment]
Closing this, as it's been a while without activity on this. @forrestp, please reopen this, if you're still having this issue.
