### ISSUE TITLE
Injected user application won't start on first boot without connection

### ISSUE THREAD

**Issue by KemperVreden** [resin-io/resin-preload-image-script#34]
In a blogpost which mentions the `resin-preload-image-script` the author says:

> Our supervisor now supports running a preloaded application before registering with the resin.io API. This means your devices can be provisioned with an application's code loaded up and ready to go on the very first boot. Saving you bandwidth and time in the factory, and in an extreme case even allowing your device to function without ever been connected to the Internet.

but (especially) ...

> This means your devices can be provisioned with an application's code loaded up and ready to go on the very first boot.

and (readme of this repository) ...

> Using this will allow images with supervisor version above 1.0.0 to run the user application without connectivity, and without the need to download the container.

... is unfortunately not true. We are using `resin-preload-image-script` in production but we always have to connect devices to the internet. The device needs to register itself before the application is being started. If there is no connection, the application won't run.

If the device has successfully registered itself you can restart the device without connection and the application will start.

This script is a HUGE timesaver but it would be even better if the application starts on first boot without the need to connect the device to the internet!

Here's a thread on resins forum: [link](https://forums.resin.io/t/preloading-images-with-application-still-requires-registering/647)

**Comment by alexandrosm** [comment]
If this is the case, then it is definitely a bug. @pcarranzav and
@jhemsmeier do you mind commenting on this?

Also, @kemperverden, what version of the OS and the supervisor are you
using?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jhermsmeier** [comment]
I'm already looking into it, and currently setting up to test / reproduce this.

**Comment by KemperVreden** [comment]
@alexandrosm 

Host OS Version is **Resin OS 1.24.1**
Supervisor Version is **2.8.3**

Here's the output of the `resin-preload-image-script`:

[https://gist.github.com/KemperVreden/032483678ed0c4247804366973cf5741](https://gist.github.com/KemperVreden/032483678ed0c4247804366973cf5741)

**Comment by pcarranzav** [comment]
@KemperVreden @jhermsmeier @alexandrosm sorry, this is most likely the bug that was fixed in https://github.com/resin-io/resin-supervisor/pull/384 - and will be deployed with supervisor 3.0.1.

**Comment by KemperVreden** [comment]
@pcarranzav Oh that's a bit frustrating to hear since I really thought this would be a fault on our side - So we have to wait for the new version of the supervisor to be release I guess and there is no workaround? 

We are manufacturing a lot of devices in the next time and this would greatly improve the time needed to manufacture a single device.

**Comment by jhermsmeier** [comment]
I can confirm, nothing happens until the device gets network access, also on resinOS 2.
@pcarranzav is there a temporary workaround we could put in place?

**Comment by KemperVreden** [comment]
@pcarranzav @jhermsmeier What happens if I use the Resin CLI to perform `os configure <image> <uuid>` or `os initialize <image>` on the preloaded image?

**Comment by jhermsmeier** [comment]
@KemperVreden so, there's a bug in the preload script as well; the referenced pull request should fix this for supervisor version 3.0.1+ (which is available in resin OS 2), but sadly not for the older supervisors.

**Comment by KemperVreden** [comment]
@pcarranzav @jhermsmeier Today I've been testing the ResinOS 2.0 rc1 Image with latest commit of the `resin-preload-image-script` and I was able to preload and run the application without having a connection to the internet.

However. In our application we are using a personalized version of `resin-wifi-connect` and when the injected application starts up it is not going to start up the WiFi hotspot that it normally creates. Maybe this is another bug? Or is it a bug of Resin OS 2.0 because the network manager changed, something like that?

**Comment by pcarranzav** [comment]
@KemperVreden that could indeed be a bug in wifi-connect with OS 2.0 - the network manager changed but there should be support in the latest versions. Could you confirm you're using the latest wifi-connect? Otherwise, could you file a bug report in github.com/resin-io/resin-wifi-connect ? Including the logs from the device and what versions you're running will probably help us diagnose.
 (@josephroberts might know better about current status of wifi-connect with NetworkManager?)

**Comment by KemperVreden** [comment]
@pcarranzav As you I read your comment I realized that the version we are using is not the latest - Version 1.x something like that - but it was definitely before version 2.0 was released! So yes - that could be causing it ...

**Comment by alexandrosm** [comment]
yup -- the old versions of wifi-connect are for resinOS 1.x only, they
don't support network manager.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by imrehg** [comment]
@pcarranzav just checked this with resinOS `v2.0.0+rev2` / supervisor 4.1.1 (the latest release for Raspberry Pi 3) and does not seem to start the application on device start, only works when network is available.

**Comment by pcarranzav** [comment]
@imrehg  I've tracked this down to https://github.com/resin-io/resin-supervisor/issues/420 - should be safe to close this issue as it is not related to preloading, it's the supervisor as a whole that is crashing.

**Comment by jhermsmeier** [comment]
Okay, closing this then – @KemperVreden please do reopen this, if you run into issues again.

**Comment by pcarranzav** [comment]
@KemperVreden, @imrehg please follow resin-io/resin-supervisor#421 for a fix to this issue
