### ISSUE TITLE
Default registry should be registry2.resin.io

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-preload-image-script#45]
Otherwise the device will be told to redownload from there causing an unwanted app restart

**Comment by jhermsmeier** [comment]
Note to self: see [flowdock thread](https://www.flowdock.com/app/rulemotion/r-supervisor/threads/7nKF1gwXBJ8Vc9TLcy6OWwcUyW_)

**Comment by jhermsmeier** [comment]
Fixed in #48 & #49
